# -*- coding: utf-8 -*-
"""Untitled103.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSC3DSCDEReN9DthMNWaCYUkXInrHCV5
"""

import zipfile
zip_path=('/content/sample_data/archive (62).zip')
with zipfile.ZipFile(zip_path,"r") as zip_ref:
  zip_ref.extractall("/content/sample_data")

import os
print(os.listdir("/content/sample_data"))

!pip install pillow
import os
import matplotlib.pyplot as plt
from PIL import Image
base_data_path="/content/sample_data/data"
# Assuming the dataset structure is base_data_path / (train|valid|test) / class / images
# We will iterate through 'train', 'valid', and 'test' splits
dataset_splits = ['train', 'valid', 'test']

for split_name in dataset_splits:
    split_path = os.path.join(base_data_path, split_name)
    if not os.path.isdir(split_path):
        print(f"Warning: Split directory '{split_path}' not found. Skipping.")
        continue

    print(f"Exploring split: {split_name}")
    classes = os.listdir(split_path)
    for cls in classes:
        class_path = os.path.join(split_path, cls)
        # Ensure it's a directory before trying to list its contents
        if os.path.isdir(class_path):
            # Filter out directories and keep only files
            images = [f for f in os.listdir(class_path)
            if os.path.isfile(os.path.join(class_path, f))]
            print(f"  Class in {split_name}: {cls} (found {len(images)} images)")
            for img in images[:3]: # Show up to 3 images per class
                img_path = os.path.join(class_path, img)
                try:
                    img_obj = Image.open(img_path)
                    plt.imshow(img_obj)
                    plt.title(f"{split_name} - {cls} - {img}")
                    plt.axis("off")
                    plt.show()
                except Exception as e:
                    print(f"    Error opening image {img_path}: {e}")

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

import os
dataset_path="/content/sample_data/dataset/train"
class_counts={}
for class_name in os.listdir(dataset_path):
    class_folder=os.path.join(dataset_path,class_name)
    if os.path.isdir(class_folder):
        class_counts[class_name]=len(os.listdir(class_folder))
print("Class Distribution:")
for k,v in class_counts.items():
    print(f"{k}:{v}")

import random
import os

def undersample_class(folder,target_count):
  files=os.listdir(folder)
  random_files=random.sample(files,len(files)-target_count)
  for f in random_files:
    os.remove(os.path.join(folder,f))
undersample_class("/content/sample_data/dataset/train/Real",240)

import os
dataset_path="/content/sample_data/dataset/train"
class_counts={}
for class_name in os.listdir(dataset_path):
    class_folder=os.path.join(dataset_path,class_name)
    if os.path.isdir(class_folder):
        class_counts[class_name]=len(os.listdir(class_folder))
print("Class Distribution:")
for k,v in class_counts.items():
    print(f"{k}:{v}")

!pip install imagehash
!pip install pillow

from PIL import Image
import imagehash
def remove_duplicates(folder):
  hashes={}
  for filename in os.listdir(folder):
    path=os.path.join(folder,filename)
    try:
      img=Image.open(path)
      img_hash=imagehash.average_hash(img)
      if img_hash in hashes:
        print(f"Duplicate found:",filename)
        os.remove(path)
      else:
        hashes[img_hash]=filename
    except:
      print("Error reading:",filename)
base_path="/content/sample_data/dataset/train"
for cls in os.listdir(base_path):
  remove_duplicates(os.path.join(base_path,cls))

import os
dataset_path="/content/sample_data/dataset/train"
class_counts={}
for class_name in os.listdir(dataset_path):
    class_folder=os.path.join(dataset_path,class_name)
    if os.path.isdir(class_folder):
        class_counts[class_name]=len(os.listdir(class_folder))
print("Class Distribution:")
for k,v in class_counts.items():
    print(f"{k}:{v}")

#to conver same count
import random
import os

def undersample_class(folder,target_count):
  files=os.listdir(folder)
  random_files=random.sample(files,len(files)-target_count)
  for f in random_files:
    os.remove(os.path.join(folder,f))
undersample_class("/content/sample_data/dataset/train/Fake",202)

# count to check balance or not
import os
dataset_path="/content/sample_data/dataset/train"
class_counts={}
for class_name in os.listdir(dataset_path):
    class_folder=os.path.join(dataset_path,class_name)
    if os.path.isdir(class_folder):
        class_counts[class_name]=len(os.listdir(class_folder))
print("Class Distribution:")
for k,v in class_counts.items():
    print(f"{k}:{v}")

#remove the unwanted files
def check_corrupt(folder):
  for filename in os.listdir(folder):
    path=os.path.join(folder,filename)
    try:
      img=Image.open(path)
      img.verify()
    except:
      print("Corrupt image found:",filename)
      os.remove(path)
for cls in os.listdir(base_path):
  check_corrupt(os.path.join(base_path,cls))

#grey scale
from PIL import Image
import os
def convert_to_grayscale(folder):
  for filename in os.listdir(folder):
    path=os.path.join(folder,filename)
    try:
      img=Image.open(path).convert("L")
      img.save(path)
    except:
      print("Error converting:",filename)
base_path="/content/sample_data/dataset/train"
for cls in os.listdir(base_path):
  convert_to_grayscale(os.path.join(base_path,cls))



IMG_SIZE = 224
BATCH_SIZE = 32
train_gen = ImageDataGenerator(
rescale=1./255,
rotation_range=20,
zoom_range=0.2,
horizontal_flip=True
)
val_gen = ImageDataGenerator(rescale=1./255)
train_data = train_gen.flow_from_directory(
"/content/sample_data/dataset/train",
target_size=(IMG_SIZE, IMG_SIZE),
batch_size=BATCH_SIZE,
class_mode="categorical"
)
val_data = val_gen.flow_from_directory(
"/content/sample_data/dataset/val",
target_size=(IMG_SIZE, IMG_SIZE),
batch_size=BATCH_SIZE,
class_mode="categorical"
)



from tensorflow.keras.applications import MobileNetV2

base_model = MobileNetV2(weights="imagenet", include_top=False,
input_shape=(224,224,3))
base_model.trainable = False
x = GlobalAveragePooling2D()(base_model.output)
x = Dense(128, activation="relu")(x)
output = Dense(train_data.num_classes, activation="softmax")(x)
model = Model(base_model.input, output)

model.compile(
optimizer=Adam(1e-4),
loss="categorical_crossentropy",
metrics=["accuracy"]
)

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
model_checkpoint = ModelCheckpoint('medicine.h5', monitor='val_accuracy', save_best_only=True)

history=model.fit(
    train_data,
    epochs=5,
    validation_data=val_data,
    callbacks=[early_stopping,model_checkpoint]
)

loss, accuracy = model.evaluate(train_data)
print(f"Test Accuracy: {accuracy * 100:.2f}%")

base_model.trainable = True
model.compile(
optimizer=Adam(1e-5), # LOWER LR
loss="categorical_crossentropy",
metrics=["accuracy"]
)
model.fit(
train_data,
validation_data=val_data,
epochs=5
)